language: node_js
node_js:
  - lts/*

os:
  - linux
dist: focal

branches:
  only:
  - gh-pages // 対象ブランチ

cache:
  directories:
    - "node_modules"

script:
  - npm run lint

install:
  - npm install
  - npm run generate

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN // Travis CIのウェブページで設定した変数
  target-branch: main // デプロイ先ブランチ
  local-dir: dist // 対象ディレクトリ
  on:
    branch: gh-pages // 対象ブランチ